

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."attendance_status" AS ENUM (
    'present',
    'absent',
    'excused',
    'late'
);


ALTER TYPE "public"."attendance_status" OWNER TO "postgres";


CREATE TYPE "public"."level" AS ENUM (
    'beginner',
    'intermediate',
    'advanced'
);


ALTER TYPE "public"."level" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."am_i_admin"() RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$DECLARE
BEGIN
  return (select admin from public.users where id = (select auth.uid()));
END;$$;


ALTER FUNCTION "public"."am_i_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."am_i_approved"() RETURNS boolean
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
DECLARE
BEGIN
  return (select approved from public.users where id = (select auth.uid()));
END;
$$;


ALTER FUNCTION "public"."am_i_approved"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_my_org_id"() RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
DECLARE
BEGIN
  return (select organization_id from public.users where id = (select auth.uid()));
END;
$$;


ALTER FUNCTION "public"."get_my_org_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  insert into public.users (id, organization_id, email, approved)
  values (new.id, 1, new.email, false);
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."merge_users"("student1" bigint, "student2" bigint) RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
IF EXISTS (
  SELECT 1 
  FROM students s1, students s2, users 
  WHERE s1.id = student1 
  AND s2.id = student2 
  AND s1.organization = s2.organization 
  AND s1.organization = (SELECT organization_id FROM users WHERE id = (select auth.uid()))
) THEN
  UPDATE attendance SET student_id = student1 WHERE student_id = student2;

  UPDATE students
  SET grade = s2.grade
  FROM students s1, students s2
  WHERE s1.id = student1 AND s2.id = student2 AND students.id = student1;
  
  UPDATE students
  SET parent_cells = ARRAY_CAT(COALESCE(s1.parent_cells, ARRAY[]::text[]), COALESCE(s2.parent_cells, ARRAY[]::text[])),
      parent_emails = ARRAY_CAT(COALESCE(s1.parent_emails, ARRAY[]::text[]), COALESCE(s2.parent_emails, ARRAY[]::text[]))
  FROM students s1, students s2
  WHERE s1.id = student1 AND s2.id = student2 AND students.id = student1;

  DELETE FROM students WHERE id = student2;
ELSE
  RAISE 'nope';
END IF;
END;
$$;


ALTER FUNCTION "public"."merge_users"("student1" bigint, "student2" bigint) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."attendance" (
    "id" bigint NOT NULL,
    "class_id" bigint NOT NULL,
    "student_id" bigint NOT NULL,
    "level" "public"."level" NOT NULL,
    "attended_statuses" "public"."attendance_status"[],
    "organization" bigint NOT NULL
);


ALTER TABLE "public"."attendance" OWNER TO "postgres";


ALTER TABLE "public"."attendance" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."attendance_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."classes" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "dates" "date"[] NOT NULL,
    "organization" bigint NOT NULL,
    "start_date" "date" GENERATED ALWAYS AS ("dates"[1]) STORED,
    "end_date" "date" GENERATED ALWAYS AS ("dates"["array_length"("dates", 1)]) STORED
);


ALTER TABLE "public"."classes" OWNER TO "postgres";


ALTER TABLE "public"."classes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."classes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "id" bigint NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."organizations" OWNER TO "postgres";


ALTER TABLE "public"."organizations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."organizations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."students" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "grade" bigint,
    "parent_cells" "text"[] NOT NULL,
    "parent_emails" "text"[] NOT NULL,
    "organization" bigint NOT NULL
);


ALTER TABLE "public"."students" OWNER TO "postgres";


ALTER TABLE "public"."students" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."students_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "organization_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "approved" boolean DEFAULT false NOT NULL,
    "admin" boolean DEFAULT false NOT NULL,
    "email" "text"
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."classes"
    ADD CONSTRAINT "classes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."organizations"
    ADD CONSTRAINT "organizations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "students_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "public"."classes"("id");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_organization_fkey" FOREIGN KEY ("organization") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."attendance"
    ADD CONSTRAINT "attendance_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id");



ALTER TABLE ONLY "public"."classes"
    ADD CONSTRAINT "classes_organization_fkey" FOREIGN KEY ("organization") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."students"
    ADD CONSTRAINT "students_organization_fkey" FOREIGN KEY ("organization") REFERENCES "public"."organizations"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id");



CREATE POLICY "Allow delete for same organization" ON "public"."students" FOR DELETE TO "authenticated" USING ((( SELECT "users"."organization_id"
   FROM "public"."users"
  WHERE ("users"."id" = ( SELECT "auth"."uid"() AS "uid"))) = "organization"));



CREATE POLICY "Allow read for same organization" ON "public"."attendance" FOR SELECT TO "authenticated" USING ((( SELECT "users"."organization_id"
   FROM "public"."users"
  WHERE ("users"."id" = ( SELECT "auth"."uid"() AS "uid"))) = "organization"));



CREATE POLICY "Allow read for same organization" ON "public"."classes" FOR SELECT TO "authenticated" USING (("organization" = "public"."get_my_org_id"()));



CREATE POLICY "Allow read for same organization" ON "public"."students" FOR SELECT TO "authenticated" USING ((( SELECT "users"."organization_id"
   FROM "public"."users"
  WHERE ("users"."id" = "auth"."uid"())) = "organization"));



CREATE POLICY "Allow update for admins within the same organization" ON "public"."users" FOR UPDATE TO "authenticated" USING ((("organization_id" = "public"."get_my_org_id"()) AND ("public"."am_i_admin"() = true)));



CREATE POLICY "Allow update for same organization" ON "public"."attendance" FOR UPDATE TO "authenticated" USING ((( SELECT "users"."organization_id"
   FROM "public"."users"
  WHERE ("users"."id" = ( SELECT "auth"."uid"() AS "uid"))) = "organization")) WITH CHECK ((( SELECT "users"."organization_id"
   FROM "public"."users"
  WHERE ("users"."id" = ( SELECT "auth"."uid"() AS "uid"))) = "organization"));



CREATE POLICY "Allow update for same organization" ON "public"."students" FOR UPDATE TO "authenticated" USING ((( SELECT "users"."organization_id"
   FROM "public"."users"
  WHERE ("users"."id" = ( SELECT "auth"."uid"() AS "uid"))) = "organization")) WITH CHECK ((( SELECT "users"."organization_id"
   FROM "public"."users"
  WHERE ("users"."id" = ( SELECT "auth"."uid"() AS "uid"))) = "organization"));



CREATE POLICY "Enable insert for admins of same org" ON "public"."attendance" FOR INSERT TO "authenticated" WITH CHECK ((("organization" = "public"."get_my_org_id"()) AND ("public"."am_i_admin"() = true)));



CREATE POLICY "Enable insert for admins of same org" ON "public"."classes" FOR INSERT TO "authenticated" WITH CHECK ((("organization" = "public"."get_my_org_id"()) AND ("public"."am_i_admin"() = true)));



CREATE POLICY "Enable insert for admins of same org" ON "public"."students" FOR INSERT TO "authenticated" WITH CHECK ((("organization" = "public"."get_my_org_id"()) AND ("public"."am_i_admin"() = true)));



CREATE POLICY "Enable users to view data of those in same org" ON "public"."users" FOR SELECT TO "authenticated" USING ((("organization_id" = "public"."get_my_org_id"()) OR (( SELECT "auth"."uid"() AS "uid") = "id")));



ALTER TABLE "public"."attendance" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."classes" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."organizations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."students" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."am_i_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."am_i_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."am_i_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."am_i_approved"() TO "anon";
GRANT ALL ON FUNCTION "public"."am_i_approved"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."am_i_approved"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_my_org_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_my_org_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_my_org_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



REVOKE ALL ON FUNCTION "public"."merge_users"("student1" bigint, "student2" bigint) FROM PUBLIC;
GRANT ALL ON FUNCTION "public"."merge_users"("student1" bigint, "student2" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "public"."merge_users"("student1" bigint, "student2" bigint) TO "service_role";


















GRANT ALL ON TABLE "public"."attendance" TO "anon";
GRANT ALL ON TABLE "public"."attendance" TO "authenticated";
GRANT ALL ON TABLE "public"."attendance" TO "service_role";



GRANT ALL ON SEQUENCE "public"."attendance_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."attendance_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."attendance_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."classes" TO "anon";
GRANT ALL ON TABLE "public"."classes" TO "authenticated";
GRANT ALL ON TABLE "public"."classes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."classes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."classes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."classes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."organizations" TO "anon";
GRANT ALL ON TABLE "public"."organizations" TO "authenticated";
GRANT ALL ON TABLE "public"."organizations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."organizations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."organizations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."organizations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."students" TO "anon";
GRANT ALL ON TABLE "public"."students" TO "authenticated";
GRANT ALL ON TABLE "public"."students" TO "service_role";



GRANT ALL ON SEQUENCE "public"."students_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."students_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."students_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


